ALTER TABLE MEDICAL_SPECIALITY ADD UNIQUE (nameSpeciality);

ALTER TABLE MEDICAL_PROCEDURE ADD CONSTRAINT FK_MEDICALPROCEDURE_MEDICALSPECIALITY FOREIGN KEY (nameSpeciality) REFERENCES MEDICAL_SPECIALITY (nameSpeciality);
ALTER TABLE MEDICAL_PROCEDURE ADD CONSTRAINT PROCEDURE_SPECIALITY_UNIQUE UNIQUE (nameProcedure,nameSpeciality);

ALTER TABLE CLINIC ADD CONSTRAINT FK_CLINIC_ADRESSE FOREIGN KEY (idAdresse) REFERENCES ADRESSE (idAdresse);
ALTER TABLE CLINIC ADD CONSTRAINT NAME_UNIQUE UNIQUE (clinicName);
ALTER TABLE CLINIC ADD CONSTRAINT REGISTRATION_UNIQUE UNIQUE (registration);

ALTER TABLE USERS ADD UNIQUE (login);

ALTER TABLE PROFILES ADD CONSTRAINT NAME_UNIQUE UNIQUE (profileName);

ALTER TABLE USER_PROFILE ADD CONSTRAINT FK_USERSPROFILE_USERS FOREIGN KEY (login) REFERENCES USERS (login);
ALTER TABLE USER_PROFILE ADD CONSTRAINT FK_USERSPROFILE_PROFILE FOREIGN KEY (profileName) REFERENCES PROFILES (profileName);
ALTER TABLE USER_PROFILE ADD UNIQUE (login,profileName);

ALTER TABLE SECRETARY ADD CONSTRAINT FK_SECRETARY_USERS FOREIGN KEY (idUser) REFERENCES USERS (idUser);
ALTER TABLE SECRETARY ADD CONSTRAINT FK_SECRETARY_ADRESSE FOREIGN KEY (idAdresse) REFERENCES ADRESSE (idAdresse);
ALTER TABLE SECRETARY ADD CONSTRAINT FK_SECRETARY_CONTACTINFORMATION FOREIGN KEY (idContactInformation) REFERENCES CONTACT_INFORMATION (idContactInformation);

ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_USERS FOREIGN KEY (idUser) REFERENCES USERS (idUser);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_SECRETARY FOREIGN KEY (idSecretary) REFERENCES USERS (idUser);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_MEDICALSPECIALITY FOREIGN KEY (idMedicalSpeciality) REFERENCES MEDICAL_SPECIALITY (idMedicalSpeciality);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_ADRESSE FOREIGN KEY (idAdresse) REFERENCES ADRESSE (idAdresse);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_CONTACTINFORMATION FOREIGN KEY (idContactInformation) REFERENCES CONTACT_INFORMATION (idContactInformation);
ALTER TABLE DOCTOR ADD CONSTRAINT FK_DOCTOR_CLINIC FOREIGN KEY (idClinic) REFERENCES CLINIC (idClinic);
ALTER TABLE DOCTOR ADD UNIQUE (numInami);

ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_DOCTOR FOREIGN KEY (numInami) REFERENCES DOCTOR (numInami);
ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY (idPatient) REFERENCES PATIENT (idPatient);
ALTER TABLE APPOINTMENT ADD UNIQUE (numInami,dateAppointment,startTime,endTime);

ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_DOCTOR FOREIGN KEY (numInami) REFERENCES DOCTOR (numInami);
ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_ADRESSE FOREIGN KEY (idAdresse) REFERENCES ADRESSE (idAdresse);
ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_CONTACTINFORMATION FOREIGN KEY (idContactInformation) REFERENCES CONTACT_INFORMATION (idContactInformation);
ALTER TABLE PATIENT ADD CONSTRAINT FK_PATIENT_MEDICALRECORD FOREIGN KEY (idMedicalRecord) REFERENCES MEDICAL_RECORD (idMedicalRecord);
ALTER TABLE PATIENT ADD UNIQUE (numRegistrationNational);

ALTER TABLE MEDICAL_RECORD ADD CONSTRAINT FK_MEDICALRECORD_PATIENT FOREIGN KEY (idPatient) REFERENCES PATIENT (idPatient);

ALTER TABLE MEDICAL_EXAM ADD CONSTRAINT FK_MEDICALEXAM_DOCTOR FOREIGN KEY (numInami) REFERENCES DOCTOR (numInami);
ALTER TABLE MEDICAL_EXAM ADD CONSTRAINT FK_MEDICALEXAM_MEDICALRECORD FOREIGN KEY (idMedicalRecord) REFERENCES MEDICAL_RECORD (idMedicalRecord);

ALTER TABLE PATHOLOGY ADD CONSTRAINT FK_PATHOLOGY_MEDICALRECORD FOREIGN KEY (idMedicalRecord) REFERENCES MEDICAL_RECORD (idMedicalRecord);

ALTER TABLE EXAMINATION_PRESCRIPTION ADD CONSTRAINT FK_EXAMINATIONPRESCRIPTION_PATHOLOGY FOREIGN KEY (idPathology) REFERENCES PATHOLOGY (idPathology);

ALTER TABLE DRUGS_PRESCRIPTION ADD CONSTRAINT FK_DRUGSPRESCRIPTION_PATHOLOGY FOREIGN KEY (idPathology) REFERENCES PATHOLOGY (idPathology);

ALTER TABLE DRUGS ADD CONSTRAINT FK_DRUGS_DRUGS FOREIGN KEY (idDrugsRef) REFERENCES DRUGS (idDrugs);
ALTER TABLE DRUGS ADD UNIQUE (drugsName);

ALTER TABLE DRUGS_POSOLOGY ADD CONSTRAINT FK_DRUGSPOSOLOGY_DRUGSPRESCRIPTION FOREIGN KEY (idDrugsPrescription) REFERENCES DRUGS_PRESCRIPTION (idDrugsPrescription);
ALTER TABLE DRUGS_POSOLOGY ADD CONSTRAINT FK_DRUGSPOSOLOGY_DRUGS FOREIGN KEY (drugsName) REFERENCES DRUGS (drugsName);
